title: Pravin Gorlewar
logo: /assets/img/logo.png
description: AI ML Practioner - Transformation Expert | Quality Engineering Manager
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
